make apt sane
=============

--------------------------------------
echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/99norecommends
--------------------------------------


lvm
===

* create a partition with partition type 8E (linux lvm)
* +apt-get install lvm2+
* Add new volumegroup +vgcreate vg0 /dev/sda6+

libvirt + kvm
=============

* +apt-get install libvirt-bin virt-top qemu-kvm debootstrap dbus virtinst
netcat-openbsd bridge-utils vde2+

* remove all additional ips from /e/n/i

* We use vde2 to create a virtual switch for an internal network and bridge the tap
  device intern to the bridge intbr

./etc/network/interface
-------------------------------------
auto eth0
iface eth0 inet manual

auto extbr
iface extbr inet static
  address 83.246.69.170
  netmask 255.255.255.248
  broadcast 83.246.69.175
  gateway 83.246.69.169
  bridge_ports eth0
  bridge_fd 9
  bridge_hello 2
  bridge_maxage 12
  bridge_stp off

auto intbr
iface intbr inet static
  address 10.0.3.1
  netmask 255.255.255.0
  bridge_fd 9
  bridge_hello 2
  bridge_maxage 12
  bridge_stp off
  bridge_ports intern

auto intern
iface intern inet manual
    vde2-switch -t intern

-------------------------------------

LDAP
====

* +apt-get install slapd ldapvi+
* Remove old ldap db: +rm /var/lib/ldap/*(db*|bdb|log*|alock)+
* Remove slapd.d madness: +rm -rf /etc/ldap/slapd.d+

./etc/ldap/slapd.conf
------------------------------------
# This is the main slapd configuration file. See slapd.conf(5) for more
# info on the configuration options.

#######################################################################
# Global Directives:

# Features to permit
#allow bind_v2

# Schema and objectClass definitions
include         /etc/ldap/schema/core.schema
include         /etc/ldap/schema/cosine.schema
include         /etc/ldap/schema/nis.schema
include         /etc/ldap/schema/inetorgperson.schema

#ssl support
TLSCACertificateFile /etc/ldap/ssl/ca.crt
TLSCertificateFile /etc/ldap/ssl/server.crt
TLSCertificateKeyFile /etc/ldap/ssl/server.key


# Where the pid file is put. The init.d script
# will not stop the server if you change this.
pidfile         /var/run/slapd/slapd.pid

# List of arguments that were passed to the server
argsfile        /var/run/slapd/slapd.args

# Read slapd.conf(5) for possible values
loglevel        0

# Where the dynamically loaded modules are stored
modulepath	/usr/lib/ldap
moduleload	back_bdb

# The maximum number of entries that is returned for a search operation
sizelimit 500

# The tool-threads parameter sets the actual amount of cpu's that is used
# for indexing.
tool-threads 1

#######################################################################
# Specific Backend Directives for bdb:
# Backend specific directives apply to this backend until another
# 'backend' directive occurs
backend		bdb

#######################################################################
# Specific Directives for database #1, of type bdb:
# Database specific directives apply to this databasse until another
# 'database' directive occurs
database        bdb

# The base of your directory in database #1
suffix          "dc=grml,dc=org"
checkpoint 512 30

# rootdn directive for specifying a superuser on the database. This is needed
# for syncrepl.
# rootdn          "cn=admin,dc=snow-crash,dc=org"

# Where the database file are physically stored for database #1
directory       "/var/lib/ldap"

# For the Debian package we use 2MB as default but be sure to update this
# value if you have plenty of RAM
dbconfig set_cachesize 0 2097152 0

# Sven Hartge reported that he had to set this value incredibly high
# to get slapd running at all. See http://bugs.debian.org/303057
# for more information.

# Number of objects that can be locked at the same time.
dbconfig set_lk_max_objects 1500
# Number of locks (both requested and granted)
dbconfig set_lk_max_locks 1500
# Number of lockers
dbconfig set_lk_max_lockers 1500

# Indexing options for database #1
index           objectClass eq

# Save the time that the entry gets modified, for database #1
lastmod         on

# The userPassword by default can be changed
# by the owner
access to attrs=userPassword,shadowLastChange
        by dn="cn=admin,dc=grml,dc=org" write
        by anonymous auth
        by self write
        by * none

# Read access for the base (needed by sasl..)
access to dn.base="" by * read

# The admin dn has full write access, everyone else
# can read everything.
access to *
        by dn="cn=admin,dc=grml,dc=org" write
        by * read

# For Netscape Roaming support, each user gets a roaming
# profile for which they have write access to
#access to dn=".*,ou=Roaming,o=morsnet"
#        by dn="cn=admin,dc=snow-crash,dc=org" write
#        by dnattr=owner write

#######################################################################
# Specific Directives for database #2, of type 'other' (can be bdb too):
# Database specific directives apply to this databasse until another
# 'database' directive occurs
#database        <other>

# The base of your directory for database #2
#suffix		"dc=debian,dc=org"

------------------------------------

.initalize ldap db
-----------------------------------
slapadd -c < EOF

dn: dc=grml,dc=org
objectClass: top
objectClass: dcObject
objectClass: organization
o: grml.org
dc: grml

dn: cn=admin,dc=grml,dc=org
objectClass: simpleSecurityObject
objectClass: organizationalRole
cn: admin
description: LDAP administrator
userPassword: {SSHA}ctYLwzAfESce+Yok3S9f2iW9HGpdakMB

dn: ou=People,dc=grml,dc=org
ou: People
objectClass: top
objectClass: organizationalUnit
structuralObjectClass: organizationalUnit

dn: ou=Group,dc=grml,dc=org
ou: Group
objectClass: top
objectClass: organizationalUnit
structuralObjectClass: organizationalUnit

----------------------------------

* +chown -R openldap:openldap /var/lib/ldap/* /etc/ldap/slapd.conf+
* start slapd

host firewall
=============

* +apt-get install ferm+

.ferm.conf
----------------------------------
table filter {
    chain INPUT {
        policy DROP;

        # connection tracking
        mod state state INVALID DROP;
        mod state state (ESTABLISHED RELATED) ACCEPT;

        # allow local packet
        interface lo ACCEPT;

        # respond to ping
        proto icmp ACCEPT; 

        # allow SSH connections
        proto tcp dport ssh ACCEPT;
    }
    chain OUTPUT {
        policy ACCEPT;

        # connection tracking
        #mod state state INVALID DROP;
        mod state state (ESTABLISHED RELATED) ACCEPT;
    }
    chain FORWARD {
        policy DROP;

        # connection tracking
        mod state state INVALID DROP;
        mod state state (ESTABLISHED RELATED) ACCEPT;
    }
}

domain ip6 {
	table filter {
		chain INPUT {
			policy DROP;

			# connection tracking
			mod state state INVALID DROP;
			mod state state (ESTABLISHED RELATED) ACCEPT;

			policy ACCEPT;

			# respond to ping
			proto icmpv6 ACCEPT;

			# allow SSH connections
			proto tcp dport ssh ACCEPT;


		}

		chain OUTPUT {
			policy ACCEPT;

			# connection tracking
			#mod state state INVALID DROP;
			mod state state (ESTABLISHED RELATED) ACCEPT;
		}
		chain FORWARD {
			policy DROP;

			# connection tracking	
			mod state state INVALID DROP;
			mod state state (ESTABLISHED RELATED) ACCEPT;
		}
	}
}

----------------------------------


3ware tools
===========

----------------------------------
# echo 'deb http://jonas.genannt.name/debian squeeze restricted' >
    /etc/apt/sources.list.d/3dm2.list
# wget -O - http://jonas.genannt.name/debian/jonas_genannt.pub | apt-key
  add -+
# apt-get update ; apt-get install 3ware-cli-binary 3ware-3dm2-binary
---------------------------------

serial console
==============

To activate sol for the BMC/IMPI enable gettys for ttyS0. Adjust /etc/inittab
and make sure it contains

---------------------------------
T0:23:respawn:/sbin/getty -L ttyS0 9600 vt100
---------------------------------


Configure ipmi
==============

* Show lan configuration: +ipmitool lan print+
* Set ip address: +ipmitool lan set 1 ipaddr $IPADDR+
* Set netmask: +ipmitool lan set 1 netmask 255.255.255.248+
* Set default gw: +ipmitool lan set 1 defgw ipaddr $GW+

Show user list: +ipmitool user list 1+
Create a new user:

---------------------------------
ipmitool user set name 6 mru
ipmitool user set password 6 PASSWORD
---------------------------------

Test the connection: +ipmitool -I lanplus -H $IP -U mru -a sol activate+

collectd
=========

